### ISSUE TITLE
Add support for optional tracing with OpenTelemetry

### ISSUE THREAD

**Issue by ryandens** [quarkiverse/quarkus-amazon-services#1049]
Quarkus supports tracing using OpenTelemetry. As stated in this [guide](https://quarkus.io/guides/opentelemetry):

> Extensions and the libraries they provide, are directly instrumented in Quarkus. The use of the [OpenTelemetry Agent](https://opentelemetry.io/docs/instrumentation/java/automatic/) is not needed nor recommended due to context propagation issues between imperative and reactive libraries.

Many quarkus core extensions therefore [natively integrate with OpenTelemetry](https://quarkus.io/guides/opentelemetry#quarkus-extensions-using-opentelemetry). In addition, plenty of extensions on the [quarkiverse do as well]( https://github.com/search?q=repo%3Aquarkusio%2Fquarkus+path%3A%2Fextensions%5C%2F%2F+NOT+path%3A%2F%5Eextensions%5C%2Fopentelemetry%5C%2F%2F+OpenTelemetry&type=code)

At first glance, quarkus-amazon-services might not need native OpenTelemetry support, because the [OpenTelemetry aws-sdk-2.2 library-autoconfigure](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/91afc720d41072e62af0016cf52b9e4e45988a1f/instrumentation/aws-sdk/aws-sdk-2.2/library-autoconfigure/src/main/resources/software/amazon/awssdk/global/handlers/execution.interceptors) module provides a mechanism to automatically add exection interceptors for the aws sdk. However, this is not compatible with Quarkus's opentelemetry extension. Depending on the initialization order, either the OpenTelemetry `TracingExecutionInterceptor` or quarkus's OpenTelemetry instance will be instantiated first. If OpenTelemetry's `TracingExecutionInterceptor` is initialized first, Quarkus's [call to initialize the global OpenTelemetry instance](https://github.com/quarkusio/quarkus/blob/2fd3b96f69239ed0c4e01de07aabe3788dabdbbe/extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/OpenTelemetryRecorder.java#L70) will fail and cause the application startup to fail, taking down the app. This is a fragile state for an application to be in, even if initialization is ordered very carefully, so we prefer not to use the library-autoconfigure module for aws and instead we should register the execution interceptors when the clients are built.

I would like to add support for OpenTelemetry for this library. This allows for users of Quarkus, OpenTelemetry, and this library to get traces for aws sdk calls, which can be very useful. 

This can be added as an optional dependency. quarkus-langchain [checks at deployment time if the OpenTelemetry capability is present ](https://github.com/quarkiverse/quarkus-langchain4j/blob/main/core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/ToolProcessor.java#L84) and then enables tracing if it is. I think this would be a good approach.

In order to do this, we would add an optional dependency on the [aws-sdk-2.2](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/aws-sdk/aws-sdk-2.2/library) and for each `AwsClient` produced by this module optionally register the open telemetry execution interceptor.

**Comment by scrocquesel** [comment]
It could also be feasible to automatically include the Quarkus OpenTelemetry extension when `io.opentelemetry.instrumentation:opentelemetry-aws-sdk-2.2` is added, leveraging [conditional extension dependencies](https://quarkus.io/guides/conditional-extension-dependencies). This mirrors our approach to automatically integrate external extensions for supporting various client implementations (such as apache/netty/crt). For instance, this module encapsulates the Quarkus Apache extension and dynamically incorporates it when needed: [quarkiverse/quarkus-amazon-services](https://github.com/quarkiverse/quarkus-amazon-services/blob/main/common/runtime-apache-client-internal/pom.xml).

As for injecting the interceptor, you can integrate by hooking into https://github.com/quarkiverse/quarkus-amazon-services/blob/2ea2652757cc47107e13a3825fb336f328ca8526/common/deployment/src/main/java/io/quarkus/amazon/common/deployment/AbstractAmazonServiceProcessor.java#L298-L327

After each `recorder.configure` call, you can enhance the interceptor configuration with a recorder when the OTel capability is present. The snippet below illustrates how this can be achieved in a recorder:

```java
public RuntimeValue<AwsClientBuilder> addOpenTelemetry(AwsClientBuilder builder) {
    builder.overrideConfiguration(
        builder.overrideConfiguration().toBuilder()
               .addExecutionInterceptor(AwsSdkTelemetry.create(openTelemetry).newExecutionInterceptor())
               .build()
    );

    return new RuntimeValue<>(builder);
}
```

You should be able to inject the `OpenTelemetry` instance from the recorder constructor.

I just hope that it will not interfere with DynamoDb Enhanced client. For a reason I don't remember its builder is built in a STATIC_INIT recorder. So we will have to pay a little more attention to how it behaves.

**Comment by scrocquesel** [comment]
I've given it a try with conditional dependency logic. I assume most users will already have the Quarkus OpenTelemetry extension in their projects, so I've built the condition based on this package to include the AWS instrumentation package. This should align with the philosophy of other extensions.

I've kept it simple without support for configuration, as autoconfigure would have permitted. The PR is open for contributions.

**Comment by ryandens** [comment]
This makes a lot of sense to me! I don't need it for my use cases. Still, I could see it making sense to replicate the autoconfigure logic [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/aws-sdk/aws-sdk-2.2/library-autoconfigure/src/main/java/io/opentelemetry/instrumentation/awssdk/v2_2/autoconfigure/AwsSdkSingletons.java#L22). Perhaps ideally OTel would expose the logic for building an an auto-configured `AwsSdkTelemetry` object registering the interceptor, so that other frameworks can re-use the logic.

Thanks!

**Comment by scrocquesel** [comment]
@all-contributors please add @ryandens for ideas
