### ISSUE TITLE
Add  CRT as allowed sync client type

### ISSUE THREAD

**Issue by vladimirfx** [quarkiverse/quarkus-amazon-services#1074]
CRT supports both modes. In the process of adopting virtual threads, we need this type of API.

**Comment by scrocquesel** [comment]
@vladimirfx I'm a bit busy to properly complete the PR but you should be able to make some tests with virtual threads and see if any issue arise.

Let me know how it goes.

**Comment by scrocquesel** [comment]
@vladimirfx released in 2.10.0. Your feedbacks are welcome. Create new issue if necessary.

**Comment by vladimirfx** [comment]
It works, thank you!
