### ISSUE TITLE
Readme unclear about version streams for versions above 2.5.x

### ISSUE THREAD

**Issue by siksniraps** [quarkiverse/quarkus-amazon-services#1094]
The readme page lists the 3 version streams, but leaves unclear what quarkus versions corespond with versions starting from 2.6.0.

**Comment by scrocquesel** [comment]
@siksniraps would you mind give a look into the PR. Do you have a specific issue with older versions ?

**Comment by siksniraps** [comment]
@scrocquesel no specific issue. Updated readme in PR looks much clearer.
