### ISSUE TITLE
Multi-tenant aws clients

### ISSUE THREAD

**Issue by kpagratis** [quarkiverse/quarkus-amazon-services#1108]
I'm building an app where i need aws clients like S3 and SecretsManger to be configured based on incoming request information. To do this, I have a requestscoped bean which eventually gets populated with an IAM role arn. This arn is then used in the creation of a credentials provider which uses STS to get temporary tokens. 

I was hoping to use this extension but I'm running into a few issues.  Primarily, the clients and client builders are @ApplicationScoped. This would be possible if the builders were @dependent scoped since calling `build` on the aws builder mutates the internal state of the builders and throw exceptions when calling build again.

Is there something I'm missing in this extension which would help me accomplish what I'm trying to do?

I'd like to continue using this extension because of all the great work done around configuration and devservices with localstack.

Thanks!

**Comment by scrocquesel** [comment]
Could overriding configuration at request level be a solution ?

ex:
```java
public static CreateBucketRequest createBucketRequest(final String bucket) {
        return CreateBucketRequest.builder()
                .bucket(bucket)
                .overrideConfiguration(b -> b.credentialsProvider(...))
                .build();
    }
```

**Comment by kpagratis** [comment]
I suppose that would work just fine. I was unaware of that functionality! 
I'll give that a try.
Thanks!
