### ISSUE TITLE
Devservices can't communicate with each other

### ISSUE THREAD

**Issue by pfaul** [quarkiverse/quarkus-amazon-services#1123]
My use case is setting up an event based communication between two quarkus services using the sns and sqs devservices.
With the config flags "shared" I could not manage to get a successful local setup. The "shared" flag (see https://docs.quarkiverse.io/quarkus-amazon-services/dev/dev-services.html#_shared_services)
of the devservices forces two different localstack containers to be run. In this case, the SQS queue is never able to receive published events from the other localstack container (sns).

I already proposed a PR (https://github.com/quarkiverse/quarkus-amazon-services/pull/1114) as a workaround to expose the docker port of the localstack container. But obviously this would just be a workaround to the real problem: I need the SNS and SQS devservices to be able to communicate with one another between multiple quarkus applications (at least in quarkus dev mode).

Can you provide any help? Thanks in advance!

**Comment by scrocquesel** [comment]
For sqs, I tested with a producer using this configuration

```
quarkus.sqs.devservices.shared=true
quarkus.sqs.devservices.queues=Quarkus
queue.url=Quarkus # used in the app to emit message
```

and the consumer

```
quarkus.sqs.devservices.shared=true
quarkus.http.port=8081
queue.url=Quarkus # reuse the same queue
```

First start the producer and wait for localstack, then the consumer. In the console, you can press `c` to see localstack instance and you should see that the consumer is using the same container.

Shared services are not grouped by design. So you will have one instance for sns and one for sqs. Both clients will connect to the corresponding localstack.

**Comment by pfaul** [comment]
Dear @scrocquesel , 
thank you for your answer. I see you do not understand my problem. Now since code does not lie, I present to you an example project with my specific problem. Please read the readme file and start the processes.

https://github.com/pfaul/quarkus-aws-events

If you can help me configure these two projects properly, that would be awesome!
Thanks in advance!

**Comment by scrocquesel** [comment]
> Dear @scrocquesel , thank you for your answer. I see you do not understand my problem. Now since code does not lie, I present to you an example project with my specific problem. Please read the readme file and start the processes.
> 
> https://github.com/pfaul/quarkus-aws-events
> 
> If you can help me configure these two projects properly, that would be awesome! Thanks in advance!

Thank you for the reproducer. Make a lot more sense now. I pushed a PR on your repo. You need to start the consumer first and then the producer. As a consequence, everything should be set up in the consumer localstack.

**Comment by scrocquesel** [comment]
> Thanks for the PR. The changes you suggested change quite a bit of lifecycle logic though! The 'service-name' part, was missing in my application.properties.
> 
> Still I have an issue to report here: Why is it, that the 'shared' flag actively changes the value of the 'service-name'. That sounds horrific tbh! When I am configuring a service-name, I want that value to be the value I defined and not something with appended shared service names! Just imagine somone would want multiple devservices to be shared. Would the service-name look like this then? 'mylocalstack-sns-sqs-s3-ssm-kms' How should any other application know about this name then??
> 
> EDIT: And also this appending of the service name does not seem to be documented anywhere :(

It make sense. The suffix was added to distinguish stacks with the default `service-name` and isolate them by default. I guess that we can remove this suffix when the `service-name` was set to something else and let the user compose its stack, and this could be considered a bug.

**Comment by pfaul** [comment]
Dear @scrocquesel ,
Thank you very much for the support! I appreciate your effort!
