### ISSUE TITLE
S3 sync file download doesn't work

### ISSUE THREAD

**Issue by petro1** [quarkiverse/quarkus-amazon-services#1179]
The issue is that download file method should have byte[] as response content and not String
https://github.com/quarkiverse/quarkus-amazon-services/blob/main/docs/modules/ROOT/pages/amazon-s3.adoc
Replace: ResponseBuilder response = Response.ok(objectBytes.asUtf8String());
With: Response.ResponseBuilder response = Response.ok(objectBytes.asByteArray());

**Comment by scrocquesel** [comment]
Good catch would you like to contribute a PR ? You can also push a PR to the repo containing the source of the quickstart sample https://github.com/quarkusio/quarkus-quickstarts/blob/884beacd8c723877b98587d6ced5eff8c792ac7e/amazon-s3-quickstart/src/main/java/org/acme/s3/S3SyncClientResource.java#L57

**Comment by petro1** [comment]
@scrocquesel thanks for your quick check, I created this PR: https://github.com/quarkusio/quarkus-quickstarts/pull/1400
