### ISSUE TITLE
graal-sdk dependency

### ISSUE THREAD

**Issue by luneo7** [quarkiverse/quarkus-amazon-services#1181]
We should be using  nativeimage instead of graal-sdk now =]

We are seeing the following warning when building native:
```
org.graalvm.sdk:graal-sdk is present in the classpath. From Quarkus 3.8 and onwards, org.graalvm.sdk:nativeimage should be preferred. Make sure you report the issue to the maintainers of the extensions that bring it.
```

**Comment by scrocquesel** [comment]
Thank you. Hope it is just a drop in replacement. I'll make a backport for quarkus bom platform.
