### ISSUE TITLE
quarkiverse's LambdaBuildTimeConfig interface conflicts with io.quarkus's LambdaBuildTimeConfig class 

### ISSUE THREAD

**Issue by emakunin** [quarkiverse/quarkus-amazon-services#1209]
Hello,

I'm trying to use `quarkus-amazon-lambda` from `io.quarkiverse .amazonservices` to inject AWS lambda client in a service that uses

```
       <dependency>
            <!-- AWS Lambda Client injection -->
            <groupId>io.quarkiverse.amazonservices</groupId>
            <artifactId>quarkus-amazon-lambda</artifactId>
        </dependency>

        <dependency>
             <!-- My service or some async job lambda -->
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-amazon-lambda-rest</artifactId> <!-- or just quarkus-lambda -->
       <dependency>
```

I tried all available versions of quarkus and quarkiverse and theirs combinations. However it doesn't work. You can try with the version combinations mentioned in https://github.com/quarkiverse/quarkus-amazon-services.

As a result my build fails with

> [ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.8.1:build (default) on project inventory-management-rest: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.amazon.lambda.deployment.LambdaProcessor#setupClient threw an exception: java.lang.IncompatibleClassChangeError: Found class io.quarkus.amazon.lambda.runtime.LambdaBuildTimeConfig, but interface was expected
[ERROR]         at io.quarkus.amazon.lambda.deployment.LambdaProcessor.setupClient(LambdaProcessor.java:104)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:840)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]

In [this commit](https://github.com/quarkiverse/quarkus-amazon-services/commit/9377e50a406db11355bf12b32e2bb09aee50f7c8#diff-78bd91a455473a18ad0cf5d49a53628328b9d028aa1338700415629815b3b310) you added `LambdaBuildTimeConfig` **interface** that conflicts with the `LambdaBuildTimeConfig` **class** used by io.quarkus. See [io quarkus class LambdaBuildTimeConfig](https://github.com/quarkusio/quarkus/blob/86ba00e29a9a326afa02a74dd81a8228a5d04c02/extensions/amazon-lambda/runtime/src/main/java/io/quarkus/amazon/lambda/runtime/LambdaBuildTimeConfig.java)

I guess the config interface package or the interface name need to be modified. So far a workaround is to not use quarkiverse and inject clients manually.

**Comment by scrocquesel** [comment]
@radcortez Is is expected that we cannot share the root prefix in two different packages ? Is it because in we use interface mapping in the extension while quarkus is using class mapping.

**Comment by radcortez** [comment]
You can share them, but I think the issue is something else. Both classes have the same FQN `io.quarkus.amazon.lambda.runtime.LambdaBuildTimeConfig`:

https://github.com/quarkusio/quarkus/blob/86ba00e29a9a326afa02a74dd81a8228a5d04c02/extensions/amazon-lambda/runtime/src/main/java/io/quarkus/amazon/lambda/runtime/LambdaBuildTimeConfig.java
https://github.com/quarkiverse/quarkus-amazon-services/blob/9377e50a406db11355bf12b32e2bb09aee50f7c8/lambda/runtime/src/main/java/io/quarkus/amazon/lambda/runtime/LambdaBuildTimeConfig.java

**Comment by scrocquesel** [comment]
It seems there are limited solutions available:
- Alter the configuration prefix to "lambdaclient." However, this adjustment would deviate from the convention used for all other extensions, where the artifact ID of the AWS package serves as the key.
- Modify the package name prefix to `io.quarkiverse`. Historically, "io.quarkus" was utilized when the project was under the umbrella of "quarkus/quarkus." While this change should be seamless, it might pose issues for extensions like S3 and DynamoDB, which offer custom annotations.

I would vote for option 2.

**Comment by GheorgheGanea** [comment]
any news?

**Comment by emakunin** [comment]
Hi folks,

Thank you for taking a look at the problem. I apologise for the radio silence. 

I've tested the proposed fix, but it seems that there's another issue (unless I do smth. wrong) https://github.com/quarkiverse/quarkus-amazon-services/pull/1267#issuecomment-2231490200

**Comment by scrocquesel** [comment]
@emakunin @GheorgheGanea Version `3.0.0.alpha1` is out. Could you have a look at it.

**Comment by andrezimmermann** [comment]
I'm have the need to write a lambda to invoke another lambda, so I though that using the `io.quarkiverse.amazonservices:quarkus-amazon-services` LambdaClient would be the correct approach.


On 2.8.1 I get the error mentioned in this issue

```
java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.amazon.lambda.deployment.LambdaProcessor#discoverTelemetry threw an exception: java.lang.IncompatibleClassChangeError: Found class io.quarkus.amazon.lambda.runtime.LambdaBuildTimeConfig, but interface was expected
	at io.quarkus.amazon.lambda.deployment.LambdaProcessor.discoverTelemetry(LambdaProcessor.java:99)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
```

On 3.0.0.alpha1 the error below since I'm using https://quarkus.io/guides/aws-lambda

```
Caused by: java.lang.IllegalStateException: Multiple extensions registered a feature of the same name: amazon-lambda
	at io.quarkus.deployment.steps.MainClassBuildStep.build(MainClassBuildStep.java:297)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
```

**Comment by scrocquesel** [comment]
> I have the need to write a lambda to invoke another lambda, so I though that using the `io.quarkiverse.amazonservices:quarkus-amazon-services` LambdaClient would be the correct approach.
> 
> On 2.8.1 I get the error mentioned in this issue
> 
> ```
> java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
> 	[error]: Build step io.quarkus.amazon.lambda.deployment.LambdaProcessor#discoverTelemetry threw an exception: java.lang.IncompatibleClassChangeError: Found class io.quarkus.amazon.lambda.runtime.LambdaBuildTimeConfig, but interface was expected
> 	at io.quarkus.amazon.lambda.deployment.LambdaProcessor.discoverTelemetry(LambdaProcessor.java:99)
> 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
> 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
> ```
> 
> On 3.0.0.alpha1 the error below since I'm using https://quarkus.io/guides/aws-lambda
> 
> ```
> Caused by: java.lang.IllegalStateException: Multiple extensions registered a feature of the same name: amazon-lambda
> 	at io.quarkus.deployment.steps.MainClassBuildStep.build(MainClassBuildStep.java:297)
> 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
> 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
> 	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
> ```

too bad, I missed you comment after releasing. Will do a 3.0.1 with another feature name.
