### ISSUE TITLE
Is it possible to add support for the AWS Inspector API?

### ISSUE THREAD

**Issue by javaduke** [quarkiverse/quarkus-amazon-services#1234]
My project requires interaction with AWS Inspector service. Is it possible to add support for it in the future release?
Also, the README says "They also provide a common infrastructure to make it easy to add new ones." - is there any kind of tutorial or a guidance on this?

**Comment by scrocquesel** [comment]
Hello, that sounds like a valuable addition.
Although there isn't specific guidance, it's essentially a matter of copying and pasting an existing extension and then performing a search and replace. You can refer to this [PR](https://github.com/quarkiverse/quarkus-amazon-services/pull/1151/files) to see what's required.

Dev services and integration tests are done against LocalStack when possible but it seems inspector is not supported https://docs.localstack.cloud/references/coverage/ Do you know any other solutions that could be used ?

**Comment by javaduke** [comment]
> Dev services and integration tests are done against LocalStack when possible but it seems inspector is not supported https://docs.localstack.cloud/references/coverage/ Do you know any other solutions that could be used ?

Yes, I noticed that too, I'm not aware of any existing solution but I will keep looking, perhaps it's a good idea to reach out to Localstack and request a new feature :)
