### ISSUE TITLE
quarkus cognito user pool extension proxy config

### ISSUE THREAD

**Issue by maghouston** [quarkiverse/quarkus-amazon-services#1261]
we are trying to use quakus cognito userpool extension with a proxy. As mentioned in the documentation, we configure the proxy in the application.yaml as follow:
<img width="404" alt="image" src="https://github.com/quarkiverse/quarkus-amazon-services/assets/13933941/f0344934-6ffd-4380-8f4d-b384c2c5c91a">
when running the app, we get following error:
`java.base/java.lang.Thread.run(Thread.java:829)\n","errorType":"software.amazon.awssdk.services.cognitoidentityprovider.model.CognitoIdentityProviderException","**errorMessage":"Service returned HTTP status code 407 (Service: CognitoIdentityProvider, Status Code: 407, Request ID: null)**"} {"timestamp":"2024-05-06T10:08:51.137Z","sequence":865,"loggerClassName":"org.jboss.logging.Logger`

We also edited JAVA_OPTS with proxyHost, proxyUser, proxyPassword and proxyPort. we still get the same issue

Could someone help us please. Thanks in advance

**Comment by scrocquesel** [comment]
Could you provide a bit more details on the error and the proxy's required authentication type (basic, ntlm) ?
Maybe you can have more details on the 407 returned by the proxy by enabling full wire log (should be the categoy `org.apache.http.wire`)
