### ISSUE TITLE
Quarkus 3.10.0 3.10.1 3.11.0.CR1 forsing version 2.14.0 not 2.15.0

### ISSUE THREAD

**Issue by adampoplawski** [quarkiverse/quarkus-amazon-services#1270]
Hello
When I generate new Quarkus project we get:
`dependencies {
    implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))
    implementation(enforcedPlatform("${quarkusPlatformGroupId}:quarkus-amazon-services-bom:${quarkusPlatformVersion}"))
    implementation("io.quarkiverse.amazonservices:quarkus-amazon-sns")
}
`

In Quarkus 3.10.0/3.10.1/3.11.0.CR1 version of quarkus-amazon-services is 2.14.0 not 2.15.0.
Is that intended or some POM/BOM is missconfigured?
Thx for help

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus-platform/pull/1207 .

**Comment by gsmet** [comment]
@scrocquesel not sure if you had planned updating it?

@adampoplawski thanks for the report btw :).

**Comment by adampoplawski** [comment]
@gsmet no problem :) Thx for cooperation

**Comment by scrocquesel** [comment]
Thank you
