### ISSUE TITLE
Unable to inject S3Crt async client

### ISSUE THREAD

**Issue by pcasaes** [quarkiverse/quarkus-amazon-services#1335]
When using the qualifier `@S3Crt` on the async client I'm getting

```
[ERROR]   S3ResourcesTest.testResource(String)[1] » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type software.amazon.awssdk.services.s3.S3AsyncClient and qualifiers [@S3Crt]
        - injection target: org.acme.s3.S3AsyncClientResource#s3
        - declared on CLASS bean [types=[org.acme.s3.S3AsyncClientResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.s3.S3AsyncClientResource]
        The following beans match by type, but none has matching qualifiers:
        - PRODUCER METHOD bean [types=[java.lang.AutoCloseable, software.amazon.awssdk.services.s3.S3AsyncClient, software.amazon.awssdk.core.SdkClient, java.lang.Object, software.amazon.awssdk.utils.SdkAutoCloseable, software.amazon.awssdk.awscore.AwsClient], qualifiers=[@Default, @Any], target=software.amazon.awssdk.services.s3.S3AsyncClient asyncClient(), declaringBean=io.quarkus.amazon.s3.runtime.S3ClientProducer]
```

Steps to reproduce:
Download the quarkus quickstart and in the `amazon-s3-quickstart` project follow the async s3crt directions:

Add

```
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>aws-crt-client</artifactId>
        </dependency>
```

Configure

```
quarkus.s3.async-client.type=aws-crt
```

In class `S3AsyncClientResource` add the qualifer `S3Crt` to

```
    @Inject
    @S3Crt
    S3AsyncClient s3;

```

Run tests

Versions:

Quarkus 3.12.3
Quarkus Amazon 2.16.0
maven  3.9.6 
Java 21.0.4

Follow up: Issue also happens with sync client.

**Comment by pcasaes** [comment]
If we add the s3-transfer-manager dependency then it does work

```
        <dependency>
            <groupId>io.quarkiverse.amazonservices</groupId>
            <artifactId>quarkus-amazon-s3-transfer-manager</artifactId>
        </dependency>
```

No need to use the s3 transfer manager, just have the dependency.

**Comment by brunoguic** [comment]
Hey folks, I believe the PR #1342 addresses the issue. The details of the change are described within the PR itself.

To explain why the `s3-transfer-manager` dependency works: Unlike the [S3CrtProcessor](https://github.com/quarkiverse/quarkus-amazon-services/blob/4ecc71767857d476767ffd36f0fac98c1b2b7de1/s3/deployment/src/main/java/io/quarkus/amazon/s3/deployment/S3CrtProcessor.java#L78), the [S3TransferManagerProcessor](https://github.com/quarkiverse/quarkus-amazon-services/blob/4ecc71767857d476767ffd36f0fac98c1b2b7de1/s3-transfer-manager/deployment/src/main/java/io/quarkus/amazon/s3/deployment/S3TransferManagerProcessor.java#L51)always creates a new `RequireAmazonClientBuildItem`.
