### ISSUE TITLE
Unavailable paymentcryptography & paymentcryptographydata yet

### ISSUE THREAD

**Issue by yk-littlepay** [quarkiverse/quarkus-amazon-services#1341]
The AWS announced one of very important services [AWS Payment Cryptography](https://aws.amazon.com/payment-cryptography/) which plays an important role for companies that deal with payment transactions to be PCI compliant. 

On this issue, I would like to ask you to add this service (which is actually divided into 2 parts: [Control](https://docs.aws.amazon.com/payment-cryptography/latest/APIReference/index.html) and [Data](https://docs.aws.amazon.com/payment-cryptography/latest/DataAPIReference/index.html) plans).

Based on my understanding, this service from a technical point of view is a copy, an add-on or an extended version, if I may say so, of the KMS service.  Therefore, I can assume that adding this service should not be difficult and will only require double copying an existing module from KMS with appropriate changes in variable names and settings.

However, it is worth considering that since the service is relatively new, Localstack does not yet support this service.

**Comment by scrocquesel** [comment]
`paymentcryptography` and `paymentcryptographydata` are the two extensions that should be added.
