### ISSUE TITLE
@NamedDynamoDbTable applicable to parameters would enable constructor injection

### ISSUE THREAD

**Issue by scrocquesel** [quarkiverse/quarkus-amazon-services#1408]
Copy from https://github.com/quarkusio/quarkus/issues/42647#issue-2475465827

**Description**
Currently it is not possible to have

private final DynamoDbTable fooTable;

FooDao(@NamedDynamoDbTable("Foo") fooTable) {
this.fooTable = fooTable
}

Because @NamedDynamoDbTable is not applicable to method parameters. Would this be feasible?

**Implementation ideas**
No response

**Comment by nicklasweasel** [comment]
> @nicklasweasel For implementation ideas, you can wider the targets of the annotation and add support for them here
> 
> https://github.com/quarkiverse/quarkus-amazon-services/blob/e17bb8c75d4ad34726618478e228faabebbbbb93/dynamodb-enhanced/deployment/src/main/java/io/quarkus/amazon/dynamodb/enhanced/deployment/DynamodbEnhancedDbTableProcessor.java#L79

Yep. There could be a  static final "allowed kind" collection and then "if kind not in list then continue" which would get rid of the wide if in the loop. And then the allowed location of the annotation itself.

Any specific test one could use as basis for unit testing? And are there any basic docs on how to set up the development environment?
