### ISSUE TITLE
Add an integration test for Messaging SQS

### ISSUE THREAD

**Issue by scrocquesel** [quarkiverse/quarkus-amazon-services#1466]
To better test all client implementations, we need an integration test.

**Comment by adampoplawski** [comment]
sorry for delay, busy time happened. I will look into it this week.

**Comment by adampoplawski** [comment]
https://github.com/adampoplawski/quarkus-amazon-services/pull/1

**Comment by scrocquesel** [comment]
could you create a pull request in this repo from your branch

**Comment by adampoplawski** [comment]
sorry, new to contributing :)
https://github.com/quarkiverse/quarkus-amazon-services/pull/1483
