### ISSUE TITLE
Automatic start of dynamodb docker container for QuarkusTests

### ISSUE THREAD

**Issue by Temdegon** [quarkiverse/quarkus-amazon-services#173]
In our projects to write integration tests with dynamodb we use testcontainers. 
Using such TestRecourse. 
```
public class DdbLocalResource implements QuarkusTestResourceLifecycleManager {

    private static final int DYNAMODB_PORT = 8000;

    public static GenericContainer<?> dynamodb =
//            new GenericContainer<>("amazon/dynamodb-local")
            new GenericContainer<>("dimaqq/dynalite:latest")
                    .withExposedPorts(DYNAMODB_PORT);

    @Override
    public Map<String, String> start() {
        dynamodb.start();
        return Map.of(
                "quarkus.dynamodb.endpoint-override", String.format("http://%s:%s",
                        dynamodb.getContainerIpAddress(), dynamodb.getMappedPort(DYNAMODB_PORT)),
                "quarkus.dynamodb.aws.credentials.type", "static",
                "quarkus.dynamodb.aws.credentials.static-provider.access-key-id", "not-exits",
                "quarkus.dynamodb.aws.credentials.static-provider.secret-access-key", "not-exists",
                "quarkus.dynamodb.aws.region", "eu-central-1"
        );
    }
    @Override
    public void stop() {
        dynamodb.stop();
    }
}
```
Would be nice to have something like that out of the box.

**Comment by scrocquesel** [comment]
Is it different from https://www.testcontainers.org/modules/localstack/ ?

**Comment by Temdegon** [comment]
Localstack container has slow startup comparing with "amazon/dynamodb-local" and "dimaqq/dynalite". but it's not the point here.
The proposal is to have it (localstack or whatever) out of the box under the hood (or as a separate extension or library) for test and dev mode.
If you are developing with quarkus + RDS you have very nice development experience: for dev mode by default it automatically starts mysql (or postgres) container, runs existing liquibase migrations and your local dev env is ready. Same works for QuarkusTests. You just inject DataSource and it works. And for test you could even change db type for h2, and all works quick and smooth. 
But for dynamodb you have to write a test resource, starting container and providing proper options yourself. It's not a big deal of course, just one class and one annotation to your test-class... but it would be super-nice to have it working out of the box, like with traditional datasources.

**Comment by scrocquesel** [comment]
@Temdegon #254 add support for devservices. Could you give it a try and let know if the extension should support some setup at startup like S3 with the creation of bucket.

**Comment by Temdegon** [comment]
@scrocquesel I've tried the extension and it works nice for dev mode and QuarkusTest. Thanks a lot!
It would be nice to have some way of ddb tables creation, but I have no idea how it should look like.
Of course right now developer could achieve this with some custom singleton, checking current active quarkus profile, or even profile-dependent producer.
How about providing a possibility to automatically execute some custom init sh script in the localstack container? This would be flexible enough to create ddb tables (and may be populate some initial data). and also such script might be useful not only for dynamodb but for any other aws services. So, may be it should be a separate ticket.

**Comment by scrocquesel** [comment]
Great news. Could you create an issue ?

**Comment by Temdegon** [comment]
created an issue https://github.com/quarkiverse/quarkus-amazon-services/issues/303
and I think this one could be closed
