### ISSUE TITLE
Reason why extension for enhanced dynamodb client don't implemented

### ISSUE THREAD

**Issue by crionuke** [quarkiverse/quarkus-amazon-services#209]
Hi, there!
Does any reason why extension for enhanced dynamodb client don't implemented?
May be some technical limitation or etc?

**Comment by Temdegon** [comment]
Looks like it's already implemented
https://github.com/quarkiverse/quarkus-amazon-services/pull/255

and also mentioned in documentation:
https://quarkiverse.github.io/quarkiverse-docs/quarkus-amazon-services/dev/amazon-dynamodb.html

```
<dependency>
    <groupId>io.quarkiverse.amazonservices</groupId>
    <artifactId>quarkus-amazon-dynamodb-enhanced</artifactId>
</dependency>
```
