### ISSUE TITLE
Support dev services globally

### ISSUE THREAD

**Issue by scrocquesel** [quarkiverse/quarkus-amazon-services#253]
Regarding needs for [dynamodb](https://github.com/quarkiverse/quarkus-amazon-services/issues/173) and [s3](https://github.com/quarkiverse/quarkus-amazon-services/issues/173), the extension should provide support for devservices for each proposed services.

It will allow to get rid of the maven docker plugin in integration tests.

Currently, localstack is used in integration for all services but cognito. Cognito use moto.

Sharing container should be supported in dev mode. See discussion in https://github.com/quarkiverse/quarkus-amazon-services/issues/173 for some design limitation. In test mode, it would be nice to reduce footprint by having a all in one container.

**Comment by gsmet** [comment]
My understanding is that we can close this one?

**Comment by scrocquesel** [comment]
Yes
