### ISSUE TITLE
Add support for WebIdentityTokenFileCredentialsProvider

### ISSUE THREAD

**Issue by patope** [quarkiverse/quarkus-amazon-services#259]
To use AWS services from the EKS cluster's pod, you need to configure [`WebIdentityTokenFileCredentialsProvider`](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/auth/credentials/WebIdentityTokenFileCredentialsProvider.html) as credentials provider. This is not in the `DefaultCredentialsProvider`'s chain. Or a way to configure any custom AwsCredentialsProvider provider is needed.

**Comment by schmittjoaopedro** [comment]
Hello, 

Did you check if you have a dependency to the sts library of AWS SDK.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/2640413/190614334-4c37a3a1-8cbf-4d3b-8128-15bebda357e1.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/2640413/190614581-d0c0ec4f-c934-4cd4-8d8a-c3398a83113a.png)

If you use the `WebIdentityTokenFileCredentialsProvider` this class depends on `WebIdentityCredentialsUtils` that depends on the STS library to get the credentials and assume the role:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/2640413/190614761-031adcf9-f619-4e17-830c-973d89606e70.png)
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/2640413/190614787-e035b012-8f20-44ce-825f-1f0b88c85517.png)

By doing that it should work. Notice that `WebIdentityTokenFileCredentialsProvider` will require the following ENV variables to be set: `AWS_REGION`, `AWS_ROLE_ARN`, and `AWS_WEB_IDENTITY_TOKEN_FILE`.

**Comment by scrocquesel** [comment]
Closed by https://github.com/quarkiverse/quarkus-amazon-services/pull/591

```pom.xml
        <dependency>
            <groupId>io.quarkiverse.amazonservices</groupId>
            <artifactId>quarkus-amazon-sts</artifactId>
        </dependency>
```

should provide native support for `WebIdentityTokenCredentialsProviderFactory`.
