### ISSUE TITLE
After upgrading from 1.1.3 to 1.3.0 DynamoDB client broken for real AWS DynamoDB service

### ISSUE THREAD

**Issue by c0va23** [quarkiverse/quarkus-amazon-services#311]
Hi! After upgrade quarkus from 2.12.3 to 2.13.1 (with upgrading `quarkus-amazon-services` from 1.1.3 to 1.3.0) all ours DynamoDB client failed on real DynamoDB service (on mock server - all still work).

Explicitly we not provide any DynamoDB properties. 

DynamoDB client call throws errors like this:
[dynamodb-ssl-error.txt](https://github.com/quarkiverse/quarkus-amazon-services/files/9764207/dynamodb-ssl-error.txt)

If i set property `quarkus.dynamodb.async-client.tls-trust-managers-provider.type` to `trust-all` issue fixed, but this not look as solution for production.

Look like this broken by [this](https://github.com/quarkiverse/quarkus-amazon-services/compare/1.1.3...1.3.0#diff-9a5b4977192422c9872c2478c1c032a8c340abeb3f139f2796fa4caebc916349R26-R32) changes.

**Comment by c0va23** [comment]
@gsmet, on 1.2.0 i have same issue

**Comment by gsmet** [comment]
Fixed and I started releasing 1.3.1.
