### ISSUE TITLE
EventBridge support

### ISSUE THREAD

**Issue by einarjohnson** [quarkiverse/quarkus-amazon-services#318]
Hello all,
I was wondering if there are any plans to create an extension for EventBridge? I assume I can build a native Quarkus executable
using the https://aws.amazon.com/blogs/developer/graalvm-native-image-support-in-the-aws-sdk-for-java-2-x/  but it would be nice to get the plug-and-play benefit of an extension.

**Comment by scrocquesel** [comment]
2.9.0 is out with support for eventbridge
