### ISSUE TITLE
Is there a version of quarkus-amazon-dynamodb that doesn't require Netty?

### ISSUE THREAD

**Issue by yortch** [quarkiverse/quarkus-amazon-services#348]
We've been using the quarkus-amazon-dynamodb extension and has worked great for us, including native builds. However the `netty-handler` library is getting flagged by Veracode as having a MitM vulnerability all the way to the latest versions (https://sca.analysiscenter.veracode.com/vulnerability-database/libraries/netty-handler/java/maven/lid-6250). I tried excluding `quarkus-netty` from the build, but it won't compile without it.

**Comment by knuspertante** [comment]
probably relates to #458

**Comment by gsmet** [comment]
@franz1981 any insights on the Netty vulnerability? Is it actually serious?

**Comment by franz1981** [comment]
In te vulnerability report link it seems related Netty 5, while we use Netty 4.1, so we shouldn't be affected

**Comment by gsmet** [comment]
I don't know, it says:
181 Versions Affected
1 Safe Versions

but there are no details so...

**Comment by franz1981** [comment]
Yep, so it's affected by long time and I suppose is a known one so...I will ping the Netty team anyway

**Comment by gsmet** [comment]
@yortch given you are using this tool, do you have access to more data? At least a CVE number or something similar?

**Comment by yortch** [comment]
Sure, here's the link with more details: https://sca.analysiscenter.veracode.com/vulnerability-database/security/sca/vulnerability/sid-22277/summary

**Vulnerability SRCCLR-SID-22277 Man-in-the-Middle (MitM) Vulnerability in the Netty/Handler library**
netty-handler is vulnerable to man-in-the-middle attacks. The library uses an SSLEngine that does not verify certificate hostnames when establishing connections with a server by default. This allows an attacker to potentially intercept and modify network traffic in a successful man-in-the-middle attack.

**Comment by scrocquesel** [comment]
I guess this default behavior is mitigated by the default tls trust manager provider that should use system keystore.

**Comment by scrocquesel** [comment]
I'm considering removing the transitive dependency on Netty. It appears to have been added erroneously from the outset, as it is not necessary for users of sync clients.
However, this could be a breaking change for users of the asynchronous client who have not added 'io.quarkus:quarkus-netty', as this was not explicitly stated in the doc where it says to add  'software.amazon.awssdk:netty-nio-client'.

Even with this change, the only alternative to not using Netty would be to use sync client. If you do need an async implementation, there is a preview PR adding support for aws crt async client.

**Comment by scrocquesel** [comment]
Since https://github.com/quarkiverse/quarkus-amazon-services/releases/tag/2.2.0, you can use a sync implementation without quarkus-netty forcibly added.

**Comment by scrocquesel** [comment]
Forgot to say, that it will come a bit latter on 1.x. I'm waiting for a fix in quarkus that should come with the next quarkus 2.17 release.

**Comment by scrocquesel** [comment]
@yortch [1.9.0](https://github.com/quarkiverse/quarkus-amazon-services/releases/tag/1.9.0) (Quarkus 2.16.x) is out and remove hard dependency on Netty. If you use sync client, Netty should not show up anymore in dependency tree.

If you want to go async, [2.4.0](https://github.com/quarkiverse/quarkus-amazon-services/releases/tag/2.4.0) (Quarkus 3.x) introduce experimental support for aws crt client.
