### ISSUE TITLE
Specifying additional localstack services

### ISSUE THREAD

**Issue by kevinross** [quarkiverse/quarkus-amazon-services#370]
I noted that properties for localstack get passed to it via `quarkus.aws.devservices.localstack.container-properties.[*]=*`, so I tried using this to add a `SERVICES` value in _the hope_ that devservices would see that and append others to it rather than simply clobbering it with the values from the `BuildItem`s.

Spoiler: it clobbers it.

I've looked around and couldn't find anything that would help. The "golden path" of writing an extension to do this with a `DevServicesLocalStackProviderBuildItem` is _way_ overkill^(1) for the use case of enabling additional localstack services IMO^(2).

Would this clobbering of `SERVICES` be considered a bug? If not, consider this my vote for it to be one and to start the conversation.

(1) not to mention issues including the extension's gradle project into a non-extension gradle project so it can be used without having to publish it, but I digress
(2) that's not to say that extensions should _not_ be written, just that for the use case of "enabling extra localstack services" it's not necessary

**Comment by scrocquesel** [comment]
Services should normally be handled automatically depending the services used in the project. Are you adding extra services because you need them to interact with an another project that used it ? Would you need it for both test mode and dev mode ?

**Comment by kevinross** [comment]
My use case involves services not already implemented as an extension; ie if I wanted to have localstack enable the service, I'd have to write the quarkus extension for it first, even if I had no plans to use the extension and was only using it to configure localstack.

If the extension existed, I'd depend on it, create a no-op class to expose the API client, and mark it unremovable so it'd be kept during build.

If quarkus respected an existing config property (presumably set via env var, but the entire config source hierarchy is in scope by design) for $SERVICES and appended to it instead of overwriting, that would solve this problem. 

TBD would be making sure it was exposed outside of the container (if it needed extra ports, etc, how quarkus would deal with that, if at all), but I'd be happy with just having the service enabled and leaving me to my own devices to get it exposed to the outside world.

**Comment by kevinross** [comment]
Cloned, built, tested and the additional service is passed in!

------

Apparently, testcontainers defaults to "EAGER_SERVICE_LOADING=0", which means "SERVICES" is ignored entirely and all services are "available" but not started/enabled; this means if quarkus _keeps_ the default as-is, this work isn't needed :( , but if the default is ever changed (ie to make enabling services explicit vs implicit), this work _would_ be needed.

(I'm in the "explicit over implicit" camp, but won't lose any sleep if the default is kept)

**Comment by scrocquesel** [comment]
> Cloned, built, tested and the additional service is passed in!
> 
> Apparently, testcontainers defaults to "EAGER_SERVICE_LOADING=0", which means "SERVICES" is ignored entirely and all services are "available" but not started/enabled; this means if quarkus _keeps_ the default as-is, this work isn't needed :( , but if the default is ever changed (ie to make enabling services explicit vs implicit), this work _would_ be needed.
> 
> (I'm in the "explicit over implicit" camp, but won't lose any sleep if the default is kept)

Right, SERVICES is also now deprecated (https://docs.localstack.cloud/references/configuration/#deprecated). LocalStack seems to have done some perf improvement and made lazy starting of services a defacto. I guess we can keep calling `withServices` for a while for those using older version of the docker image.

But then, I wonder why you can't access services not added to the container SERVICES ?

**Comment by kevinross** [comment]
I probably *could* have, I hadn't actually looked at the container's logs
until now (combination of not needing to and an assumption that only
enabled services will work, because of the SERVICES var), just the logs
from java.

That said, probably a good idea to still have this option for the reason
you mentioned. Also, if localstack gates any more features behind a pro
subscription (as is their right, I'm not opposed to people making money!),
it lets us use an older version that might need this capability.
