### ISSUE TITLE
[Extension Proposal] Support for AWS step functions

### ISSUE THREAD

**Issue by Cs4r** [quarkiverse/quarkus-amazon-services#440]
Dear quarkiverse team,

I propose adding an extension to [quarkus-amazon-services](https://github.com/quarkiverse/quarkus-amazon-services) for interacting with Amazon Web Services (AWS) Step Functions.

AWS Step Functions is a fully managed service that enables developers to build, test, and run workflows that execute as a series of steps. These workflows can be triggered by a variety of events, such as an HTTP request, a scheduled time, or the completion of a downstream task. Step Functions make it easy to coordinate and execute complex, long-running processes asynchronously, which can be particularly useful in microservices architectures.

Adding an extension for AWS Step Functions to quarkiverse would enable developers to easily incorporate Step Functions into their Quarkus applications, making it possible to build, deploy, and run workflows that coordinate the execution of microservices and other components.

The extension would be called something like `io.quarkiverse.amazonservices:quarkus-amazon-stepfunctions`

I believe that this extension would be a valuable addition to quarkiverse, as it would allow developers to take advantage of the benefits of Step Functions when building cloud-native applications.

Thank you for considering this proposal.

hashtags: #quarkus #aws #stepfunctions #microservices #cloudnative #workflow #coordination #async #extension proposal

Sincerely,
César Aguilera

**Comment by scrocquesel** [comment]
If I understood correctly, you want to wrap `software.amazon.awssdk:sfn` as `io.quarkiverse.amazonservices:quarkus-amazon-sfn`. Would you like to submit a pull request? Adding a new extension is simple. You can refer to https://github.com/quarkiverse/quarkus-amazon-services/pull/591 to see what needs to be added.

**Comment by bwhove** [comment]
Hi, I'm also interested in this extension and will probably start working on this if it's not already being picked up.

**Comment by scrocquesel** [comment]
2.9.0 is out with sfn support. I'm closing this. Feel free to open new issue if necessary.
