### ISSUE TITLE
Upgrade to Quarkus 3.0

### ISSUE THREAD

**Issue by ShaikDayan** [quarkiverse/quarkus-amazon-services#477]
Hello @team Can we upgrade the quarkus-amazon-services package to support Quarkus 3.0?

Quarkus migration tips: https://github.com/quarkiverse/quarkiverse/wiki/Migrating-to-Quarkus-3.x

**Comment by gsmet** [comment]
That's on my list but I don't see any reason to rush it given we are still at alpha phase for Quarkus 3.

**Comment by ppalaga** [comment]
Getting a Quarkus 3 release of quarkus-amazon-services would help Camel Quarkus to move on with testing against Quarkus 3. @gsmet is there any chance to get some sort of an Alpha release?

**Comment by gsmet** [comment]
Now that I switched Quarkus main to 3, I will work on publishing 3-compatible versions for all the critical extensions.
