### ISSUE TITLE
Interface type inconsistency

### ISSUE THREAD

**Issue by alexsiaba** [quarkiverse/quarkus-amazon-services#56]
`com.google.common.base.Predicate` is not consistent with `java.util.stream.Stream` interface.
`java.util.function.Predicate` should be used instead
Although those two types share the same interface (in most cases) sometimes [this one](https://guava.dev/releases/19.0/api/docs/com/google/common/base/Predicate.html) takes over the intended one and it can lead to some very regretful time losses.

**Comment by gsmet** [comment]
Could you be more precise? Because I have no idea what you're talking about. Thanks.

**Comment by alexsiaba** [comment]
ye, sorry, I was referring to [this](https://github.com/quarkiverse/quarkus-amazon-services/blob/cb4104bf559876073d19707a9b7db98eb47ff7f8/common/deployment/src/main/java/io/quarkus/amazon/common/deployment/AmazonServicesClientsProcessor.java#L11) being used [here](https://github.com/quarkiverse/quarkus-amazon-services/blob/main/common/deployment/src/main/java/io/quarkus/amazon/common/deployment/AmazonServicesClientsProcessor.java#L111) with `java.util.stream.Stream.filter` method. Although `com.google.common.base.Predicate` interface is compatible _in most cases_ with the [filter](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#filter-java.util.function.Predicate-) method, sometimes, however, it is not, and I think, it's better to use `java.util.function.Predicate` instead

**Comment by alexsiaba** [comment]
you know, I can make a pr, if that can make things easier to understand @gsmet

**Comment by gsmet** [comment]
Thanks, I created https://github.com/quarkiverse/quarkus-amazon-services/pull/59 to fix it.
