### ISSUE TITLE
feature: please add timestream (timestream-query, timestream-write)

### ISSUE THREAD

**Issue by SingingBush** [quarkiverse/quarkus-amazon-services#576]
It would be very useful to my organisation if Quarkus Amazon Services included timestream. Currently we have to pull in the _software.amazon.awssdk_ version

```
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>timestreamwrite</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>software.amazon.awssdk</groupId>
                    <artifactId>apache-client</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>software.amazon.awssdk</groupId>
                    <artifactId>netty-nio-client</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>timestreamquery</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>software.amazon.awssdk</groupId>
                    <artifactId>apache-client</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>software.amazon.awssdk</groupId>
                    <artifactId>netty-nio-client</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

testing this is a real pain as it's not picked up as a service by localstack when running tests:

```
[io.qua.ama.com.dep.DevServicesLocalStackProcessor] (build-29) Amazon Dev Services for localstack (sqs, dynamodb) started
```

so we end up with limited integration tests of this part of our stack

**Comment by SingingBush** [comment]
I forked quarkus-amazon-services with the intention making PR for adding timestream support but it seems that this project is tied to whichever servers are supported by [testcontainers-java](https://github.com/testcontainers/testcontainers-java). I've created a similar feature request in their repo: https://github.com/testcontainers/testcontainers-java/issues/6726

If test containers adds support I'm happy to pick this up again

**Comment by scrocquesel** [comment]
We are using localstack. It has support for Timestream but it requires the non free pro version https://docs.localstack.cloud/user-guide/aws/timestream/.

**Comment by scrocquesel** [comment]
@SingingBush If you know a container image that can be used in integration test instead of localstack, that would be fine too. cognito is using moto for example.

**Comment by SingingBush** [comment]
I had a look at moto but timestream isn't in the list of aws services it supports. I've not seen an alternative
