### ISSUE TITLE
Document DevServices' requirement for a synchronous HTTP client

### ISSUE THREAD

**Issue by kdubb** [quarkiverse/quarkus-amazon-services#606]
When upgrading from `1.1.1` to `1.6.3` to use DevServices the familiar `Unable to load an HTTP implementation from any provider in the chain` error popped up.

We only use asynchronous clients so don't need a synchronous client for application code.

DevServices docs should point this requirement out *_in big bold letters_* 😏

**Comment by scrocquesel** [comment]
Thanks for pointing this out. Which services are you using ?

**Comment by kdubb** [comment]
S3, DynamoDB, and KMS.

**Comment by scrocquesel** [comment]
Latest version removed this requirement (dev services now use its own dependency)
