### ISSUE TITLE
How to use Dev Services with @QuarkusIntegrationTest

### ISSUE THREAD

**Issue by krisgerhard** [quarkiverse/quarkus-amazon-services#609]
I'm using SQS dev services succesfully in @QuarkusTest.

```
  @InjectSpy
  protected lateinit var sqsClient: SqsClient
```
```
  @BeforeAll
  fun setUp() {
    sqsClient.createQueue(CreateQueueRequest.builder().queueName("TestQueue").build())
  }
```

But in @QuarkusIntegrationTest SqsClient is not initialized. 
`kotlin.UninitializedPropertyAccessException: lateinit property sqsClient has not been initialized`

Should it be possible to use sqs dev services to test native image?

**Comment by scrocquesel** [comment]
It should work, we have IT tests here https://github.com/quarkiverse/quarkus-amazon-services/blob/main/integration-tests/src/test/java/io/quarkus/it/amazon/AmazonSqsITCase.java but clients are not injected in the test classes, due to some limitation with native testing https://quarkus.io/guides/getting-started-testing#native-executable-testing.

You can try get the configuration and create a client manually using [DevServicesContext](https://quarkus.io/guides/getting-started-testing#testing-dev-services).

**Comment by krisgerhard** [comment]
Thank you! My use-case should be covered with https://github.com/quarkiverse/quarkus-amazon-services/pull/566

**Comment by scrocquesel** [comment]
Meanwhile, you may use init scripts. Have a look to https://github.com/quarkiverse/quarkus-amazon-services/pull/317

**Comment by krisgerhard** [comment]
Thank you. Managed to workaround with init scripts. Although discovered that they are not working with latest LocalStack. Opened a separate issue.

**Comment by krisgerhard** [comment]
Not sure what you mean by that exactly. For @QuarkusIntegrationTest it really doesn't matter where you run your production application. DevServices use testcontainers and spin up Docker containers for integration tests. In this case I'm using custom init scripts to create the queues my tests are using.

`application.properties`
```
quarkus.aws.devservices.localstack.init-scripts-folder=src/test/resources/localstack-init
quarkus.aws.devservices.localstack.init-completion-msg=completed
```
src/test/resources/localstack-init/create-queues.sh
```
#!/usr/bin/env bash
## TODO Can be replaced with https://github.com/quarkiverse/quarkus-amazon-services/commit/afcd123fdce8b198496b6953da767858ebb5a56c
set -euo pipefail

# enable debug
set -x


echo "configuring sqs"
echo "==================="
LOCALSTACK_HOST=localhost
AWS_REGION=us-east-1


# https://docs.aws.amazon.com/cli/latest/reference/sqs/create-queue.html
create_queue() {
  local QUEUE_NAME_TO_CREATE=$1
  awslocal --endpoint-url=http://${LOCALSTACK_HOST}:4566 sqs create-queue --queue-name ${QUEUE_NAME_TO_CREATE} --region ${AWS_REGION} --attributes VisibilityTimeout=30
}

create_queue "YourQueueNameHere"
echo "completed"

```
Reference to created queue: `http://127.0.0.1:52549/000000000000/YourQueueNameHere`

**Comment by ygyg70** [comment]
I am getting connection refused when the address http://127.0.0.1:{mapped_port} is used
http://{localstack_address_in_bridge_network}:4566 works, however this is not what is injected by the framework

**Comment by ygyg70** [comment]
Seems that I am hitting this issue https://github.com/quarkusio/quarkus/issues/34049

**Comment by ygyg70** [comment]
Override has to be dynamic, after the IP address of the localstack container is known.
This can be done from a QuarkusTestResourceLifecycleManager, only issue is that you cannot override the properties from dev services..
Just got https://github.com/quarkusio/quarkus/pull/34685 approved to change that behavior
