### ISSUE TITLE
Issue with DNS?

### ISSUE THREAD

**Issue by MarcAntoine-Beauvais** [quarkiverse/quarkus-amazon-services#662]
Hello,
I am trying to connect to a S3 with an URL having DNS value and it doesn't work.
For example, localhost is not working, to make it work I have to use 127.0.0.1
Same thing when using in a docker, I cannot use DNS values generated by docker but I have to use the raw IP address.

Any idea how to solve this?

It is working for any other service such as a database..

**Comment by scrocquesel** [comment]
S3 behaves differently than any other extensions regarding DNS. AWS is now using [host-based bucket endpoints](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html).
When using localhost, you should configure [path-style access](https://quarkiverse.github.io/quarkiverse-docs/quarkus-amazon-services/dev/amazon-s3.html#quarkus-amazon-s3_quarkus.s3.path-style-access), if you don't want to configure all you bucket name as subdomain of localhost.

As an alternative, LocalStack is [conveniently providing a wildcard DNS](https://docs.localstack.cloud/getting-started/faq/#is-using-localhostlocalstackcloud4566-to-set-as-the-endpoint-for-aws-services-recommended) that resolve to 127.0.01 and is compatible with host-based endpoints.

Currently, Dev services for AWS does use path-style access to connect to the LocalStack container it starts.

**Comment by MarcAntoine-Beauvais** [comment]
Oh I see, thanks for the explanations!
