### ISSUE TITLE
Can't detect the S3Client configuration in native mode

### ISSUE THREAD

**Issue by nicolasduminil** [quarkiverse/quarkus-amazon-services#789]
In a Quarkus 2.16.6.Final application, I'm using software.amazon.awssdk.services.s3.S3Client class. I have declared the following dependency:

    ...
    <dependency>
      <groupId>io.quarkus.platform</groupId>
      <artifactId>quarkus-amazon-services-bom</artifactId>
      <version>${quarkus.platform.version}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
    ...
    <dependency>
      <groupId>io.quarkiverse.amazonservices</groupId>
      <artifactId>quarkus-amazon-s3</artifactId>
    </dependency>
    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>url-connection-client</artifactId>
    </dependency>
    ...

And in the source code I'm injecting:

    @Inject
    S3Client s3client;

Everything worsk as expected in JVM mode but, in native mode, the following exception is raised:

    Caused by: java.lang.IllegalStateException: The S3Client is required but has not been detected/configured.
    at io.quarkus.amazon.s3.runtime.S3ClientProducer.client(S3ClientProducer.java:34)
    at  io.quarkus.amazon.s3.runtime.S3ClientProducer_ProducerMethod_client_c3e44358d8bba829ee2f6ae63d6f9ef0b4609f3a_Bean.create(Unknown Source)
    at io.quarkus.amazon.s3.runtime.S3ClientProducer_ProducerMethod_client_c3e44358d8bba829ee2f6ae63d6f9ef0b4609f3a_Bean.create(Unknown Source)
    at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)

What am I doing wrong here ? My understanding is that the default value of the quarkus-amazon-s3_quarkus.s3.sync-client.type is url, so I don't need to declare it in application.properties, right ?

Many thanks in advance for any help.

Kind regards,

Nicolas

**Comment by nicolasduminil** [comment]
Some more results after carefully testing: it appears that simply injecting the s3 client, as below:

    @Inject
    S3Client s3client;

Results in NPE as s3client is null. In order to avoid this exception, I need to initialize it as follows:

    s3client = S3Client.builder().build();

Then I get the following exception:

    Multiple HTTP implementations were found on the classpath. To avoid non-deterministic loading implementations, please explicitly provide an HTTP client via the client builders, set the software.amazon.awssdk.http.service.impl system property with the FQCN of the HTTP service to use as the default, or remove all but one HTTP implementation from the classpath

After googling for a while, I came with that which seems to work:

    s3client = S3Client.builder().httpClient(UrlConnectionHttpClient.builder().build()).build();

It doesn't have much sense to set the HTTP client here because, be default, it is UrlConnectionHttpClient. Of course, nothing of these happens when running in JVM mode where the injection doesn't result to null and doesn't raise NPE and where I don't need to explicitly initialize the client, once injected.

**Comment by nicolasduminil** [comment]
Anyone please ?

**Comment by argenstijn** [comment]
I guess the main quesiton is, in which class do you inject the s3? 

Is this class managed by quarkus?

**Comment by argenstijn** [comment]
Can you  attach the maven/etc project to this issue so i can have a look?

**Comment by scrocquesel** [comment]
> Is a class annotated with @QuarkusTest a class managed by quarkus ?

You cannot use @inject in native mode. See [Native Executable Testing](https://quarkus.io/guides/getting-started-testing#native-executable-testing) for more information
