### ISSUE TITLE
How to perform unit tests using AWS not localstack ?

### ISSUE THREAD

**Issue by nicolasduminil** [quarkiverse/quarkus-amazon-services#795]
Hello,
While localstack is very useful for unit testing, in some cases one might want to use AWS. I know that, in this case, the tests aren't anymore unit ones but integration ones. However, it's still interesting to be able to use CDI and inject stuff, which wouldn't be possible in true integration tests. Would it be possible to use AWS instead of localstack and how ?

Many thanks in advance.
Nicolas

**Comment by scrocquesel** [comment]
Hello,

You can simply disable dev services and ensure you have proper configuration for aws. You can use different profiles to help you have both tests with dev services and others without.

[How to disable dev services](https://quarkiverse.github.io/quarkiverse-docs/quarkus-amazon-services/dev/dev-services.html#_enabling_disabling_dev_services_for_amazon_services)
[Test with different profiles](https://quarkus.io/guides/getting-started-testing#testing_different_profiles)
