### ISSUE TITLE
@QuarkusIntegrationTest - connection refused trying to use localstack dev services

### ISSUE THREAD

**Issue by ygyg70** [quarkiverse/quarkus-amazon-services#834]
Integration tests work with jar launch mode, however dev services address is not configured correctly when the app runs inside Docker:

Argument passed to Docker run:
QUARKUS_SQS_ENDPOINT_OVERRIDE=http://127.0.0.1:{mapped_localstack_ip_address}

Should be:
QUARKUS_SQS_ENDPOINT_OVERRIDE=http://{ip_address_of_localstack_container_on_bridge_network}:4566

Using Quarkus version 3.2.0

**Comment by scrocquesel** [comment]
@ygyg70 Dev services is using testcontainers under the hood, have you tried  https://java.testcontainers.org/features/configuration/#customizing-docker-host-detection ?

**Comment by ygyg70** [comment]
Digging into the code, seems the issue is in Quarkus project (https://github.com/quarkusio/quarkus/issues/34049), will close this issue
