### ISSUE TITLE
Add support for S3 CRT client

### ISSUE THREAD

**Issue by scrocquesel** [quarkiverse/quarkus-amazon-services#860]
Now that we have support for aws-crt, we could add support for the [s3 crt client](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/crt-based-s3-client.html).

**Comment by stefvanderweldevolksbanknl** [comment]
We should have an `aws-crt-s3` client-type.

**Comment by scrocquesel** [comment]
> We need an `aws-crt-s3` client-type.

Do you need to configure these parameters ?

```
// .initialReadBufferSizeInBytes(null)
// .maxConcurrency(null)
// .minimumPartSizeInBytes(null)
// .targetThroughputInGbps(null)
```

The `client-type` is an enum shared across all extensions, and it won't allow the use of both implementations in the same project. I don't know if one really need both. If not, it would imply that the AWS CRT-based S3 client could seamlessly replace the AWS CRT-based HTTP client, and the `crt` client type could be used to inject it.

In any case, I've just pushed a draft pull request to introduce support for the S3 CRT flavor with the qualifier @S3Crt.

```
    @Inject
    S3AsyncClient s3AsyncClient; // classic client (could be netty or crt based sdkAsyncHttpClient)

    @Inject
    @S3Crt
    S3AsyncClient s3CrtAsyncClient; // AWS CRT-based S3 client
```

Let me know your thoughts on what you believe is the most suitable approach.

**Comment by nielsvhaldvb** [comment]
We don't expect a need to configure these properties as long as they are not required by the sdk or have proper defaults.

**Comment by scrocquesel** [comment]
I'm a bit busy, and I'm still not set on whether we should use a qualifier, support the `S3CrtAsyncClient` interface as an injection point, or create a new `quarkus-amazon-s3-crt` package.

The latter option would inject into the same `S3AsyncClient` interface and could lead to interference if both `quarkus-amazon-s3` and `quarkus-amazon-s3-crt` are present in the project. Actually, producers produce a `@DefaultBean` qualified instance, and both packages cannot provide such qualified beans as Quarkus may not be able to determine which producer to use as the default implementation. So, I don't think this is a good idea.

**Comment by stefvanderweldevolksbanknl** [comment]
> In any case, I've just pushed a draft pull request to introduce support for the S3 CRT flavor with the qualifier @s3crt.

I like this idea.

> > We need an `aws-crt-s3` client-type.
> 
> Do you need to configure these parameters ?
> 
> ```
> // .initialReadBufferSizeInBytes(null)
> // .maxConcurrency(null)
> // .minimumPartSizeInBytes(null)
> // .targetThroughputInGbps(null)
> ```

Do you think it's possible to pass these parameters in the annotation?

**Comment by scrocquesel** [comment]
> > In any case, I've just pushed a draft pull request to introduce support for the S3 CRT flavor with the qualifier @s3crt.
> 
> I like this idea.
> 
> > > We need an `aws-crt-s3` client-type.
> > 
> > 
> > Do you need to configure these parameters ?
> > ```
> > // .initialReadBufferSizeInBytes(null)
> > // .maxConcurrency(null)
> > // .minimumPartSizeInBytes(null)
> > // .targetThroughputInGbps(null)
> > ```
> 
> Do you think it's possible to pass these parameters in the annotation?

I opted for config properties `quarkus.s3.crt-client.*`.
