### ISSUE TITLE
Quarkus 3.3+ and quarkus-amazon-services 2.5.0 crash my integration tests on the console

### ISSUE THREAD

**Issue by External-Marcus** [quarkiverse/quarkus-amazon-services#917]
Hi, 

When using Quarkus 3.2.Final all is fine - But when I am upgrading my pom to 3.3 /3.3.1,
I get the following thread block:
https://pastebin.com/7E1yiF4g

The error is gone when I am either going back to 3.2, or removing all my S3 Bucket related code.
Interestingly enough - the  S3 Bucket related integration test passes sucessfully and never gets stuck.

Any ideas?

Further info - for my tests I wrote a little test mock:

@ApplicationScoped
class S3ClientTestService {

    private final S3Client s3Client;
    private final String bucketName;

    @Inject
    public S3ClientTestService(S3Client s3Client, @ConfigProperty(name = "s3.bucket.name") String bucketName) {
        this.s3Client = s3Client;
        this.bucketName = bucketName;
    }

    void uploadFile(String objectKey, FileType fileType, File file) {
        PutObjectRequest putObjectRequest = PutObjectRequest.builder()
                .bucket(bucketName)
                .key(objectKey)
                .contentType(fileType.mimeType())
                .acl(ObjectCannedACL.PUBLIC_READ)
                .build();

        s3Client.putObject(putObjectRequest, RequestBody.fromFile(file));
    }

    void deleteAllFiles() {
        try {
            ListObjectsV2Request listObjectsV2Request = ListObjectsV2Request.builder()
                    .bucket(bucketName)
                    .build();
            ListObjectsV2Response listObjectsV2Response;
            do {
                listObjectsV2Response = s3Client.listObjectsV2(listObjectsV2Request);
                for (S3Object s3Object : listObjectsV2Response.contents()) {
                    DeleteObjectRequest request = DeleteObjectRequest.builder()
                            .bucket(bucketName)
                            .key(s3Object.key())
                            .build();
                    s3Client.deleteObject(request);
                }
            } while (listObjectsV2Response.isTruncated());
        } catch (S3Exception e) {
            throw new RuntimeException("S3 exception for bucket name: " + bucketName, e);
        }
    }
}

Anything wrong with this code, maybe?

**Comment by scrocquesel** [comment]
Hello,

I guess you experience the same issue as https://github.com/quarkiverse/quarkus-amazon-services/issues/862  with jdk 19 or higher.

**Comment by External-Marcus** [comment]
Possible. I use Java 20, upgrading to 21 in a few days.
So I know you will say Java 17.. but.. I will still ask - when will you fix it ?
Thanks :)

**Comment by scrocquesel** [comment]
The issue is not on our side. The bug lies deep within the AWS SDK, and currently, they only support JDK 9, 11 and 17. Quarkus also supports versions 11 and 17 only at the moment. I am not aware of the plans for moving forward.

I have opened an [issue on AWS's GitHub repository](https://github.com/aws/aws-sdk-java-v2/issues/4395).

**Comment by External-Marcus** [comment]
I see and thanks a lot for opening the issue on the AWS's GitHub repository.

Being the average kind of customer, please don't be suprise when I am still trying it -
Well it worked before, not sure way, maybe by magic or randomly.. but it worked, until 3.3 was released - so it should be possible to also fix this from your end, or at least to provide some temporary nasty hack that makes it for the time being?

I would hate to find out that I am stuck with 3.2 for the next few months or years :(
Planning to upgrade to Java 21 in a few weeks and love to always be on latest and greatest :)

**Comment by gsmet** [comment]
> I would hate to find out that I am stuck with 3.2 for the next few months or years :(

The good news is that it’s an LTS version :)

FWIW, Quarkus should work with any JDK superior to 11. We unfortunately cannot run the whole test suite with JDK 21 because Gradle is lagging a bit and we have the Gradle plugin build embedded.

**Comment by External-Marcus** [comment]
Ditch Gradle, no one needs it ;)

**Comment by scrocquesel** [comment]
@External-Marcus A PR is being reviewed at AWS side. Meanwhile, you can use https://github.com/quarkiverse/quarkus-amazon-services/releases/tag/2.5.1 (please read the changelog for more information)

**Comment by michaeldimchuk** [comment]
Tested this out with Quarkus `3.4.1`, Quarkus Amazon Services `2.5.2` and AWS SDK `2.21.15`, I'm no longer seeing tests hang as a result of the executor getting deadlocked.

**Comment by External-Marcus** [comment]
Can't confirm. Still open for me with Java 20. Tried with Quarkus 3.4.1 and  and AWS SDK 2.21.15, As @michaeldimchuk stated - Quarkus Amazon Services 2.5.2 must be a typo as IMHO it does not exist.

**Comment by scrocquesel** [comment]
> Can't confirm. Still open for me with Java 20. Tried with Quarkus 3.4.1 and  and AWS SDK 2.21.15, As @michaeldimchuk stated - Quarkus Amazon Services 2.5.2 must be a typo as IMHO it does not exist. 

https://github.com/quarkiverse/quarkus-amazon-services/releases/tag/2.5.2

And 2.5.3 is out with the fix implemented in AWS sdk.

You must use the bomb from the extension and not from the quarkus platform.

**Comment by gsmet** [comment]
I updated Quarkus Amazon Services to 2.5.3 for Quarkus 3.5.2 so using Quarkus 3.5.2 should be OK.
