### ISSUE TITLE
@SqsListener for Quarkus

### ISSUE THREAD

**Issue by iamgul** [quarkiverse/quarkus-amazon-services#940]
I searched in Quarkus documentation and the internet and documentation show how to receive messages from SQS using get call, but I want to receive the message a way springboot works with @sqsListener i.e. as soon as the message is sent to Sqs it will be polled, I am searching for its equivalent in quarkus. If there is any possibility for this please let me know, Thank you in advance.

**Comment by scrocquesel** [comment]
AFAIK, there is no equivalent. SQS works only by polling messages (short or long). Whatever solution you come up with, you'll be polling at the end of the journey and would have to deal with all the intricacies and cost management that it implies.

For messaging purposes, Quarkus relies on [SmallRye Reactive Messaging](https://github.com/smallrye/smallrye-reactive-messaging). Quarkus Amazon Services extension currently provide support for producing AWS SDK clients and for native builds.

The challenge would be to create a connector on top of both of those libraries. While it would be a great addition to Quarkiverse, it is a bit out of scope for this project. If you are interested, you can create your own Quarkiverse extension.

Off the top of my head, using SmallRye Messaging, you may have a worker thread that does the polling in a `while(true)` loop (or a scheduled one). It would use an [emitter](https://smallrye.io/smallrye-reactive-messaging/4.9.0/concepts/emitter/). Then you could have an equivalent of `@SqsListener` with `@Incoming`.

Alternatively, you can have AWS Lambda triggered by SQS, which may be a simpler solution and more oriented towards cloud architecture.
