### ISSUE TITLE
Support awssdk version 2.21.0

### ISSUE THREAD

**Issue by scrocquesel** [quarkiverse/quarkus-amazon-services#958]
Version 2.21.0 introduces a major internal refactor of authentication and more tight coupling with optional `aws-crt` package. Native build is impacted as it cannot find class definitions.

A potential solution is to provide native substitution using `org.graalvm.sdk:graal-sdk` to eliminate any dependency on `aws-crt` when the package is not included.

For eg.

```
public class Crc32ChecksumSubstitutions {
    static final String SOFTWARE_AMAZON_AWSSDK_CRT_PACKAGE = "software.amazon.awssdk.crt";

    static final class IsCrtAbsent implements BooleanSupplier {
        @Override
        public boolean getAsBoolean() {
            return !Arrays.asList(Package.getPackages()).stream()
                    .map(p -> p.getName())
                    .anyMatch(p -> p.equals(SOFTWARE_AMAZON_AWSSDK_CRT_PACKAGE));
        }
    }

    @TargetClass(Crc32CChecksum.class)
    static final class Target_Crc32CChecksum {

        @Alias
        private Checksum crc32c;

        @Substitute
        public Target_Crc32CChecksum() {
            crc32c = SdkCrc32CChecksum.create();
        }
    }
}
```

**Comment by hamburml** [comment]
Isn't that a bug in the AWS SDK then? I thought the aws sdk for java 2.x has graalvm support https://aws.amazon.com/blogs/developer/graalvm-native-image-support-in-the-aws-sdk-for-java-2-x/

**Comment by scrocquesel** [comment]
> Isn't that a bug in the AWS SDK then? I thought the aws sdk for java 2.x has graalvm support https://aws.amazon.com/blogs/developer/graalvm-native-image-support-in-the-aws-sdk-for-java-2-x/

AFAIK, aws-crt is not yet supported https://github.com/aws/aws-sdk-java-v2/issues/2948.

For their CI tests, they use graalvm 22.3 and quarkus is using 23.0. Maybe there is a difference. Could be interesting to test https://github.com/aws/aws-sdk-java-v2/tree/master/test/sdk-native-image-test with mandrel 23.0

**Comment by scrocquesel** [comment]
> > Isn't that a bug in the AWS SDK then? I thought the aws sdk for java 2.x has graalvm support https://aws.amazon.com/blogs/developer/graalvm-native-image-support-in-the-aws-sdk-for-java-2-x/
> 
> AFAIK, aws-crt is not yet supported [aws/aws-sdk-java-v2#2948](https://github.com/aws/aws-sdk-java-v2/issues/2948).
> 
> But it is indeed interesting that their CI tests passed. They use graalvm 22.3 and quarkus is using 23.0. Maybe there is a difference. Could be interesting to test https://github.com/aws/aws-sdk-java-v2/tree/master/test/sdk-native-image-test with mandrel 23.0


Build passed. I saw that aws-sdk is building the native image without `--link-at-build-time` which require types to be fully defined at native executable build time.
