### ISSUE TITLE
Update localstack

### ISSUE THREAD

**Issue by adampoplawski** [quarkiverse/quarkus-amazon-services#971]
Hello
According to docs localstack default is 1.4.0. Is there a reason to keep that old version?
https://docs.quarkiverse.io/quarkus-amazon-services/dev/dev-services.html

**Comment by scrocquesel** [comment]
No good reason per see apart init script configuration but it should support 2.x.
I made a PR to bump it to 2.3.x https://github.com/quarkiverse/quarkus-amazon-services/pull/973.
